  zap_baseline:
    machine: true
    steps:
      - checkout

      - run: |
          docker pull owasp/zap2docker-stable:2.10.0
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap owasp/zap2docker-stable:2.10.0 zap-baseline.py -t ${
htpps://www.celestialsys.com} -J zap-output.json || true

      - store_artifacts:
          path: zap-output.json
          destination: zap-artifact
